#####################################################################################################
# general
#####################################################################################################

[project]
name = "LLMOps"
version = "0.1.0"
description = "Advanced RAG system with LangGraph."
authors = [
    {name = "Dmitry Zhigalo"}
]
readme = "README.md"
requires-python = ">=3.12,<3.13"

#####################################################################################################
# dependencies
#####################################################################################################

dependencies = [
    "click>=8.3.0",
    "datasets>=4.2.0",
    "ddgs>=9.6.1",
    "langchain-community>=0.4.0",
    "langchain-huggingface>=1.0.0",
    "langchain-openai>=1.0.0",
    "langchain-qdrant>=1.1.0",
    "langchain-text-splitters>=1.0.0",
    "langgraph>=1.0.0",
    "mlflow[genai]>=3.6.0",
    "openai>=2.7.0",
    "pydantic>=2.12.0",
    "pydantic-settings>=2.11.0",
    "pyyaml>=6.0.3",
    "ragas>=0.3.5",
    "sentence-transformers>=5.1.1",
    "tiktoken>=0.12.0",
    "torch>=2.7.1",
]

[tool.uv.sources]
torch = { url = "https://download.pytorch.org/whl/cpu-cxx11-abi/torch-2.7.1%2Bcpu.cxx11.abi-cp312-cp312-linux_x86_64.whl" }

[dependency-groups]
lint = [
    "isort>=7.0.0",
    "poethepoet>=0.37.0",
    "ruff>=0.12.10",
]

#####################################################################################################
# ruff
#####################################################################################################

[tool.ruff]
line-length = 150
target-version = "py312"
cache-dir = "~/.cache/ruff"
preview = true
exclude = [
  ".git",
  ".venv",
  "rag/prompts*",
]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 88
quote-style = "single"

[tool.ruff.lint]
select = [
    "B",      # flake8-bugbear
    "C4",     # flake8-comprehensions
    "COM",    # flake8-commas
    "PIE",    # flake8-pie
    "T20",    # flake8-print
    "RET",    # flake8-return
    "SIM",    # flake8-simplify
    "N",      # pep8-naming
    "N",      # pep8-naming
    "E",      # pycodestyle errors
    "W",      # pycodestyle warnings
    "PL",     # pylint
    "F",      # pyflakes
    "UP",     # pyupgrade
    "RUF",    # ruff-specific rules
    "TRY",    # tryceratops
    "D101",
    "D103",
]
allowed-confusables = ["›"]
ignore = [
    "E302", # blank-lines-top-level
    "E305", # blank-lines-after-function-or-class
]

[tool.ruff.lint.per-file-ignores]
"rag/workflow.py" = ["PLR6301"]  # Ignore method could be a function, class method, or static method

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

#####################################################################################################
# isort
#####################################################################################################

[tool.isort]
py_version = 312
line_length = 120
combine_as_imports = true
combine_star = true
lexicographical = true
src_paths = ['rag', 'data']
remove_redundant_aliases = false
include_trailing_comma = true
color_output = true
multi_line_output = 3

#####################################################################################################
# poe
#####################################################################################################

[tool.poe.tasks]
isort = "isort --jobs -1 ."
