services:
  qdrant_db:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant-vdb
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ${CACHE_STORAGE_DIR:-./opt}/qdrant_data:/qdrant/storage

configs:
  qdrant_config:
    content: |
      log_level: DEBUG


networks:
  qdrant-network:
    driver: bridge